---
title: "handle the labelled data in mrpkit"
author: "Dewi Amaliah"
date: "12/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)

```

The data:

1. Smoke data (NYTS2017) could be downloaded [here](https://www.cdc.gov/tobacco/data_statistics/surveys/nyts/data/index.html)
2. Wages data could be downloaded [here](https://onedrive.live.com/?authkey=%21AP6PMk0EBH%2Dx59M&cid=07C4D937B78DE3CA&id=7C4D937B78DE3CA%2127454&parId=7C4D937B78DE3CA%2127445&o=OneUp)
3. titanic data could be downloaded [here](https://drive.google.com/file/d/1FTE_0cFH8mroRrgTvtWVsPMTDvUD71T4/view?usp=sharing)

```{r}
smoke <- read_sas("nyts2020.sas7bdat")
wages <- read_sav("Wages.sav")
shape <- mrpkit::shape_survey
titan <- read_sav("titanic.sav")
```


```{r}

# here, the example is using titanic data
data <- wages

# this function will keep the factor, character, binary response, and labelled data (which is essentially a factor data, and if it is, it would be factorize in the next code)
keep <- function(x) is.factor(x) || is.character(x) || length(unique(x)) == 2 || !is.null(attr(x, "labels"))

# subset the variable that is in the keep criteria
data_use <- data[, sapply(data, keep), drop = FALSE]

# factorize the data that has a value labels
data_factorize <- as.data.frame(lapply(data_use, function(x) 
  if(!is.null(attr(x, "labels"))) {
    if (0 %in% x){as.factor(names(attr(x, "labels")[as.numeric(paste(x))+1]))}
    else {as.factor(names(attr(x, "labels")[as.numeric(paste(x))]))}}
  else 
    {x}))

# the downside of data_factorize is that it omit the variable's label (i.e., the question)
# hence, to extract the question, we will use data_use, instead of data factorize
# data factorize will only be used to extract the response, and its change the value of variable (according to its level, so might be this gonna be used in the next stage?)

#### extract the question 

# select the variable that has a label and the class of its label is character. It is because, the variables that has labels, but doesn't have question label, would be counted as variable that has a question label, but its class is numeric, for example, sex and south in wages data, and sex in the titanic data. 
q_labelled <- dplyr::select_if(data_use, function(x) !is.null(attr(x, "label")) & class(attr(x, "label")) == "character")

# extract the question
questions <- lapply(q_labelled, function(x) setNames(attr(x, "label"), names(x)))


# select the variable that does not have label or having a label, but its label is numeric (for example, sex and south in wages data, and sex in the titanic data)
q_not_labelled <- dplyr::select_if(data_use, function(x) is.null(attr(x, "label")) | (!is.null(attr(x, "label")) & class(attr(x, "label")) == "numeric"))

# append the list of questions
append(questions, setNames(as.list(colnames(q_not_labelled)), colnames(q_not_labelled)))
```


```{r}
# get the response from the factorize data
responses <- lapply(data_factorize, function(x) if (is.factor(x)) levels(x) else unique(x))
responses
```
























