test_that("questions and responses autogenerated if not provided and
          data provided contains haven-labelled data", {
            expect_warning(
              x <- SurveyData$new(feline_survey_haven),
              "No 'questions' and 'responses' provided.
              Using all factor, character, binary variables, and haven-labelled data in 'data' by default.")

            expect_equal(
              x$questions(),
              list(age1 = "Which age group are you?",
                   gender = "gender",
                   pet_own = "Please select your pet",
                   y = "Will you adopt any new cat?")
            )
            expect_equal(
              x$responses(),
              list(
                age1 = c("18-25", "26-35", "36-45", "46-55", "56-65", "66-75", "76-90"),
                gender = c("male", "female", "nonbinary"),
                pet_own = c("cat", "dog", "kitten", "puppy"),
                y = c(2, 1)
              )
            )
})
